---
title: "Markdown Class"
author: "MAJ Nick Reisweber"
date: "12/6/2021"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo = FALSE}
klippy::klippy()
```

# Level 1 header

## subheader

###### subest of headers

horizontal line

------------------------------------------------------------------------

## text formatting

*italics*

**bold**

~~strikethrough~~

superscript^2^

[google](https://google.com)

[underline]{.ul}

| column 1 | column 2 | column 3 |
|:---------|:--------:|---------:|
| value 1  | value 2  |  value 3 |

| Col1 | Col2 | Col3 |
|------|:----:|------|
| 1    |      |      |
|      |  5   |      |
|      |  1   | 2    |

: best table ever

this is the formula $y = mx+b^2$

see the equation below $$y = mx+b^2$$


ctrl+alt+i

```{r histogram, message=FALSE, warning=FALSE}
#anything in here treated like code
#were going to make a plot
library(tidyverse)
library(palmerpenguins)
data("penguins")

penguins %>% 
  ggplot(aes(x=flipper_length_mm))+geom_histogram()

```

